### ISSUE TITLE
Fix the 26 pre-existing tsc errors in apps/web, then make type-check blocking

### ISSUE THREAD

**Issue by navigreen311** [navigreen311/animaforge#19]
Split out of #17.

`tsc --noEmit` in `apps/web` reports 33 errors. 7 are being fixed by the infra/UI track; the other **26 sit outside its file ownership** and need their owners.

The `type-check` job runs but does **not** block merge until these are cleared. The exclusion is documented inline next to `ci-passed` in `ci.yml`.

These were invisible until now: `npm ci` failed before `tsc` ever ran (since PR #16), and on top of that an unescaped apostrophe in `lib/email/triggers.ts:119` made the file unparseable, which masked everything else behind 7 bogus syntax errors. Both are fixed in #17.

## Remaining, by owner

**`components/scenegraph/SceneGraphEditor.tsx` — 6**
`TS2322`/`TS2345` at lines 50, 97-100, 195. Node literals are missing the required `visible: boolean` from `FullNode`.

**`components/live/BroadcastOverlayDesigner.tsx` — 6**
`TS2322` at lines 39-44.

**`lib/storage/upload.ts` — 3**
- 106, 139 `TS2307`: `Cannot find module 'sharp'` — the dependency is imported but not in any `package.json`. Either add it or drop the import.
- 132 `TS2345`: `Buffer` not assignable to `Uint8Array<ArrayBufferLike>` (Node 20+ type change).

**`app/page.tsx` — 2**
`TS2305` at lines 18, 19 — module has no such exported member.

**`app/api/markers/[id]/route.ts` — 1**
`TS1117` at line 22 — duplicate object literal key.

**`(dashboard)/audio/page.tsx`, `(dashboard)/marketplace/page.tsx`, `(dashboard)/characters/page.tsx`, `(dashboard)/projects/[id]/characters/page.tsx` — 8**
Left to the avatar/characters track to avoid colliding with in-flight work.

## Done when

All of the above are fixed and `type-check` is back in the blocking list in `ci-passed`.
